all: clean
	cp asgn4.py while-ss
	chmod u+x while-ss

clean:
	rm -rf while-ss
	rm -rf *.pyc

move: clean
	rm ../cse210A-asgtest-master/cse210A-asgtest-hw4-whiless/asgn4.py
	cp asgn4.py ../cse210A-asgtest-master/cse210A-asgtest-hw4-whiless/
