all: clean
	cp asgn2.py while
	chmod u+x while

clean:
	rm -rf while
	rm -rf *.pyc

move: clean
	rm ../cse210A-asgtest-master/cse210A-asgtest-hw2-while/asgn2.py
	cp asgn2.py ../cse210A-asgtest-master/cse210A-asgtest-hw2-while/
